let hosts = [
  {
    id: 1,
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@example.com',
    phone: '+1234567890',
    bio: "I'm passionate about providing unforgettable experiences for my guests...",
    languages: ['English', 'Spanish'],
    superhost: true,
    subscriptionDate: '2023-01-15',
    hostStartingDate: '2022-05-10',
    reviews: [
      {
        publishedDate: '2024-06-05',
        comment: 'The host was really kind and everything went well',
        userId: 8,
        value: 5,
      },
      {
        publishedDate: '2024-06-10',
        comment: 'Great location and clean accommodation. Would stay again!',
        userId: 12,
        value: 4,
      },
    ],
    answerRate: 0.95,
    averageTimeToAnswer: 2,
    avatar: 'https://example.com/avatar1.jpg',
  },
  {
    id: 2,
    firstName: 'Alice',
    lastName: 'Smith',
    email: 'alice.smith@example.com',
    phone: '+1987654321',
    bio: 'I enjoy meeting new people and sharing experiences...',
    languages: ['English', 'French'],
    superhost: false,
    subscriptionDate: '2022-11-20',
    hostStartingDate: '2022-03-15',
    reviews: [
      {
        publishedDate: '2024-07-01',
        comment: 'The host was very accommodating and friendly.',
        userId: 5,
        value: 5,
      },
      {
        publishedDate: '2024-07-05',
        comment: 'Nice place, excellent hospitality!',
        userId: 9,
        value: 4,
      },
    ],
    answerRate: 0.92,
    averageTimeToAnswer: 3,
    avatar: 'https://example.com/avatar2.jpg',
  },
  {
    id: 3,
    firstName: 'Michael',
    lastName: 'Johnson',
    email: 'michael.johnson@example.com',
    phone: '+1472583690',
    bio: 'Lover of travel and hosting amazing stays...',
    languages: ['English', 'Italian'],
    superhost: true,
    subscriptionDate: '2021-07-10',
    hostStartingDate: '2021-01-05',
    reviews: [
      {
        publishedDate: '2024-05-20',
        comment: 'Wonderful host, great experience!',
        userId: 6,
        value: 5,
      },
      {
        publishedDate: '2024-06-18',
        comment: 'Perfect stay, very attentive host.',
        userId: 10,
        value: 5,
      },
    ],
    answerRate: 0.97,
    averageTimeToAnswer: 1,
    avatar: 'https://example.com/avatar3.jpg',
  },
  {
    id: 4,
    firstName: 'Emma',
    lastName: 'Brown',
    email: 'emma.brown@example.com',
    phone: '+1230984567',
    bio: 'I love hosting and making new friends from around the world...',
    languages: ['English', 'German'],
    superhost: false,
    subscriptionDate: '2022-05-30',
    hostStartingDate: '2022-02-20',
    reviews: [
      {
        publishedDate: '2024-04-15',
        comment: 'Emma was a great host. Highly recommend!',
        userId: 3,
        value: 4,
      },
      {
        publishedDate: '2024-04-28',
        comment: 'Lovely place and friendly host.',
        userId: 4,
        value: 5,
      },
    ],
    answerRate: 0.9,
    averageTimeToAnswer: 4,
    avatar: 'https://example.com/avatar4.jpg',
  },
  {
    id: 5,
    firstName: 'Liam',
    lastName: 'Jones',
    email: 'liam.jones@example.com',
    phone: '+1123456789',
    bio: "I strive to make every guest's stay comfortable and enjoyable...",
    languages: ['English', 'Portuguese'],
    superhost: true,
    subscriptionDate: '2023-03-22',
    hostStartingDate: '2022-07-18',
    reviews: [
      {
        publishedDate: '2024-03-10',
        comment: 'Fantastic host and great place.',
        userId: 1,
        value: 5,
      },
      {
        publishedDate: '2024-03-22',
        comment: 'Very welcoming and helpful.',
        userId: 2,
        value: 4,
      },
    ],
    answerRate: 0.94,
    averageTimeToAnswer: 2,
    avatar: 'https://example.com/avatar5.jpg',
  },
  {
    id: 6,
    firstName: 'Sophia',
    lastName: 'Davis',
    email: 'sophia.davis@example.com',
    phone: '+1234569870',
    bio: 'Making every stay special and unique...',
    languages: ['English', 'Spanish'],
    superhost: false,
    subscriptionDate: '2021-12-01',
    hostStartingDate: '2021-03-14',
    reviews: [
      {
        publishedDate: '2024-02-05',
        comment: 'Sophia is an excellent host!',
        userId: 7,
        value: 5,
      },
      {
        publishedDate: '2024-02-18',
        comment: 'Great stay, very attentive.',
        userId: 8,
        value: 4,
      },
    ],
    answerRate: 0.91,
    averageTimeToAnswer: 3,
    avatar: 'https://example.com/avatar6.jpg',
  },
  {
    id: 7,
    firstName: 'James',
    lastName: 'Miller',
    email: 'james.miller@example.com',
    phone: '+1098765432',
    bio: 'Dedicated to providing the best guest experiences...',
    languages: ['English', 'French'],
    superhost: true,
    subscriptionDate: '2020-08-15',
    hostStartingDate: '2019-12-10',
    reviews: [
      {
        publishedDate: '2024-01-20',
        comment: 'James was an outstanding host.',
        userId: 9,
        value: 5,
      },
      {
        publishedDate: '2024-01-25',
        comment: 'Very nice and comfortable stay.',
        userId: 10,
        value: 4,
      },
    ],
    answerRate: 0.96,
    averageTimeToAnswer: 1,
    avatar: 'https://example.com/avatar7.jpg',
  },
  {
    id: 8,
    firstName: 'Olivia',
    lastName: 'Wilson',
    email: 'olivia.wilson@example.com',
    phone: '+1123987456',
    bio: 'I love making new friends and hosting travelers...',
    languages: ['English', 'Italian'],
    superhost: false,
    subscriptionDate: '2021-05-25',
    hostStartingDate: '2020-10-12',
    reviews: [
      {
        publishedDate: '2024-05-10',
        comment: 'Olivia was very kind and helpful.',
        userId: 11,
        value: 4,
      },
      {
        publishedDate: '2024-05-15',
        comment: 'Nice place and host.',
        userId: 12,
        value: 5,
      },
    ],
    answerRate: 0.89,
    averageTimeToAnswer: 4,
    avatar: 'https://example.com/avatar8.jpg',
  },
  {
    id: 9,
    firstName: 'William',
    lastName: 'Taylor',
    email: 'william.taylor@example.com',
    phone: '+1234567891',
    bio: 'Passionate about hosting and ensuring a great stay...',
    languages: ['English', 'German'],
    superhost: true,
    subscriptionDate: '2020-09-10',
    hostStartingDate: '2019-11-25',
    reviews: [
      {
        publishedDate: '2024-03-05',
        comment: 'William was a wonderful host.',
        userId: 3,
        value: 5,
      },
      {
        publishedDate: '2024-03-12',
        comment: 'Great hospitality!',
        userId: 4,
        value: 4,
      },
    ],
    answerRate: 0.93,
    averageTimeToAnswer: 2,
    avatar: 'https://example.com/avatar9.jpg',
  },
  {
    id: 10,
    firstName: 'Emily',
    lastName: 'Anderson',
    email: 'emily.anderson@example.com',
    phone: '+1239876540',
    bio: 'Ensuring comfort and memorable stays for all guests...',
    languages: ['English', 'Portuguese'],
    superhost: false,
    subscriptionDate: '2022-07-15',
    hostStartingDate: '2021-11-30',
    reviews: [
      {
        publishedDate: '2024-04-20',
        comment: 'Emily was very welcoming.',
        userId: 5,
        value: 5,
      },
      {
        publishedDate: '2024-04-25',
        comment: 'Enjoyed my stay very much.',
        userId: 6,
        value: 4,
      },
    ],
    answerRate: 0.9,
    averageTimeToAnswer: 3,
    avatar: 'https://example.com/avatar10.jpg',
  },
  {
    id: 11,
    firstName: 'Benjamin',
    lastName: 'Thomas',
    email: 'benjamin.thomas@example.com',
    phone: '+1345678901',
    bio: 'I love hosting and making every guest feel at home...',
    languages: ['English', 'Spanish'],
    superhost: true,
    subscriptionDate: '2021-03-22',
    hostStartingDate: '2020-09-18',
    reviews: [
      {
        publishedDate: '2024-06-15',
        comment: 'Benjamin was a great host!',
        userId: 7,
        value: 5,
      },
      {
        publishedDate: '2024-06-18',
        comment: 'Very kind and helpful.',
        userId: 8,
        value: 4,
      },
    ],
    answerRate: 0.94,
    averageTimeToAnswer: 2,
    avatar: 'https://example.com/avatar11.jpg',
  },
  {
    id: 12,
    firstName: 'Isabella',
    lastName: 'Martinez',
    email: 'isabella.martinez@example.com',
    phone: '+1098765123',
    bio: 'Hosting with care and attention to detail...',
    languages: ['English', 'French'],
    superhost: false,
    subscriptionDate: '2023-08-25',
    hostStartingDate: '2022-12-01',
    reviews: [
      {
        publishedDate: '2024-07-05',
        comment: 'Isabella was a fantastic host!',
        userId: 9,
        value: 5,
      },
      {
        publishedDate: '2024-07-10',
        comment: 'Very nice stay, would recommend.',
        userId: 10,
        value: 4,
      },
    ],
    answerRate: 0.91,
    averageTimeToAnswer: 3,
    avatar: 'https://example.com/avatar12.jpg',
  },
  {
    id: 13,
    firstName: 'Henry',
    lastName: 'Hernandez',
    email: 'henry.hernandez@example.com',
    phone: '+1456789012',
    bio: 'Enjoying hosting and meeting new people...',
    languages: ['English', 'Italian'],
    superhost: true,
    subscriptionDate: '2022-04-12',
    hostStartingDate: '2021-08-20',
    reviews: [
      {
        publishedDate: '2024-05-25',
        comment: 'Henry is an excellent host.',
        userId: 11,
        value: 5,
      },
      {
        publishedDate: '2024-06-01',
        comment: 'Great stay and wonderful host.',
        userId: 12,
        value: 4,
      },
    ],
    answerRate: 0.93,
    averageTimeToAnswer: 2,
    avatar: 'https://example.com/avatar13.jpg',
  },
  {
    id: 14,
    firstName: 'Mia',
    lastName: 'Lopez',
    email: 'mia.lopez@example.com',
    phone: '+1987654123',
    bio: "I love hosting and making every guest's stay special...",
    languages: ['English', 'German'],
    superhost: false,
    subscriptionDate: '2023-02-18',
    hostStartingDate: '2022-06-22',
    reviews: [
      {
        publishedDate: '2024-03-10',
        comment: 'Mia was a wonderful host!',
        userId: 3,
        value: 5,
      },
      {
        publishedDate: '2024-03-20',
        comment: 'Lovely place and great host.',
        userId: 4,
        value: 4,
      },
    ],
    answerRate: 0.89,
    averageTimeToAnswer: 4,
    avatar: 'https://example.com/avatar14.jpg',
  },
  {
    id: 15,
    firstName: 'Daniel',
    lastName: 'Garcia',
    email: 'daniel.garcia@example.com',
    phone: '+1234567895',
    bio: 'Passionate about providing a great guest experience...',
    languages: ['English', 'Portuguese'],
    superhost: true,
    subscriptionDate: '2021-06-14',
    hostStartingDate: '2020-12-05',
    reviews: [
      {
        publishedDate: '2024-04-05',
        comment: 'Daniel is a fantastic host.',
        userId: 1,
        value: 5,
      },
      {
        publishedDate: '2024-04-10',
        comment: 'Enjoyed the stay very much.',
        userId: 2,
        value: 4,
      },
    ],
    answerRate: 0.94,
    averageTimeToAnswer: 2,
    avatar: 'https://example.com/avatar15.jpg',
  },
  {
    id: 16,
    firstName: 'Ava',
    lastName: 'Clark',
    email: 'ava.clark@example.com',
    phone: '+1239874561',
    bio: 'Hosting with love and care for a memorable stay...',
    languages: ['English', 'Spanish'],
    superhost: false,
    subscriptionDate: '2022-11-30',
    hostStartingDate: '2022-05-18',
    reviews: [
      {
        publishedDate: '2024-05-15',
        comment: 'Ava is a great host.',
        userId: 5,
        value: 5,
      },
      {
        publishedDate: '2024-05-20',
        comment: 'Very comfortable stay.',
        userId: 6,
        value: 4,
      },
    ],
    answerRate: 0.9,
    averageTimeToAnswer: 3,
    avatar: 'https://example.com/avatar16.jpg',
  },
  {
    id: 17,
    firstName: 'Jackson',
    lastName: 'Lewis',
    email: 'jackson.lewis@example.com',
    phone: '+1987654325',
    bio: 'I love hosting and ensuring my guests have a great stay...',
    languages: ['English', 'French'],
    superhost: true,
    subscriptionDate: '2023-04-01',
    hostStartingDate: '2022-09-10',
    reviews: [
      {
        publishedDate: '2024-02-15',
        comment: 'Jackson was an amazing host!',
        userId: 7,
        value: 5,
      },
      {
        publishedDate: '2024-02-20',
        comment: 'Highly recommend this host.',
        userId: 8,
        value: 4,
      },
    ],
    answerRate: 0.95,
    averageTimeToAnswer: 2,
    avatar: 'https://example.com/avatar17.jpg',
  },
  {
    id: 18,
    firstName: 'Charlotte',
    lastName: 'Walker',
    email: 'charlotte.walker@example.com',
    phone: '+1098765436',
    bio: 'Ensuring a wonderful stay for all guests...',
    languages: ['English', 'Italian'],
    superhost: false,
    subscriptionDate: '2021-07-25',
    hostStartingDate: '2021-01-15',
    reviews: [
      {
        publishedDate: '2024-01-05',
        comment: 'Charlotte was very helpful.',
        userId: 9,
        value: 5,
      },
      {
        publishedDate: '2024-01-10',
        comment: 'Great place, enjoyed the stay.',
        userId: 10,
        value: 4,
      },
    ],
    answerRate: 0.92,
    averageTimeToAnswer: 3,
    avatar: 'https://example.com/avatar18.jpg',
  },
  {
    id: 19,
    firstName: 'Elijah',
    lastName: 'Hall',
    email: 'elijah.hall@example.com',
    phone: '+1456789234',
    bio: 'Hosting with passion and dedication...',
    languages: ['English', 'German'],
    superhost: true,
    subscriptionDate: '2022-02-18',
    hostStartingDate: '2021-08-25',
    reviews: [
      {
        publishedDate: '2024-06-01',
        comment: 'Elijah is a wonderful host.',
        userId: 11,
        value: 5,
      },
      {
        publishedDate: '2024-06-05',
        comment: 'Great experience, highly recommend.',
        userId: 12,
        value: 4,
      },
    ],
    answerRate: 0.93,
    averageTimeToAnswer: 2,
    avatar: 'https://example.com/avatar19.jpg',
  },
  {
    id: 20,
    firstName: 'Amelia',
    lastName: 'Allen',
    email: 'amelia.allen@example.com',
    phone: '+1234567898',
    bio: 'I love hosting and making every stay unique...',
    languages: ['English', 'Portuguese'],
    superhost: false,
    subscriptionDate: '2023-10-05',
    hostStartingDate: '2022-03-01',
    reviews: [
      {
        publishedDate: '2024-07-15',
        comment: 'Amelia is a fantastic host.',
        userId: 1,
        value: 5,
      },
      {
        publishedDate: '2024-07-20',
        comment: 'Very comfortable and pleasant stay.',
        userId: 2,
        value: 4,
      },
    ],
    answerRate: 0.9,
    averageTimeToAnswer: 3,
    avatar: 'https://example.com/avatar20.jpg',
  },
];

module.exports = hosts;
